version: "3.9"

services:
  sofia-nodejs:
    image: sofia-nodejs-dev
    container_name: sofia-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3010:3010"   # HTTP / STOMP
      - "9229:9229"   # Node inspector (VS Code debug)
    env_file:
      - src/.env
    command: npm run dev
